### ISSUE TITLE
开源许可

### ISSUE THREAD

**Issue by xingrz** [oldman1977/SmartProxy#2]
Hi @hedaode ,

我打算讲这个项目移植到 Google Glass。想请问这个项目使用什么开源许可？

**Comment by oldman1977** [comment]
项目使用GPL许可协议，很高兴项目对你有帮助，请自由使用吧！

------------------ 原始邮件 ------------------
发件人: "XiNGRZ";notifications@github.com;
发送时间: 2014年6月5日(星期四) 中午11:29
收件人: "hedaode/SmartProxy"SmartProxy@noreply.github.com; 
抄送: "下标越界-Mr.he"hedaode@qq.com; 
主题: [SmartProxy] 开源许可 (#2)

Hi @hedaode ,

我打算讲这个项目移植到 Google Glass。想请问这个项目使用什么开源许可？

**Comment by xingrz** [comment]
@hedaode 感谢！也建议在项目中添加 LICENSE 文件方便大家对项目提交贡献。直接在 GitHub 点击文件列表上方、项目名旁边的 + 号（或者地址 https://github.com/hedaode/SmartProxy/new/master ），文件名填入 `LICENSE`，就可以在右边「Want to use a template?」选择 GPL 协议的模板。

**Comment by oldman1977** [comment]
非常感谢，我已经加了GPLv3 License文件. 
我以前是做windows上编程的(C#)，对开源不太了解，Git也不熟悉。这是我第一次弄开源项目，希望以后多多交流。

------------------ 原始邮件 ------------------
发件人: "XiNGRZ";notifications@github.com;
发送时间: 2014年6月5日(星期四) 中午11:53
收件人: "hedaode/SmartProxy"SmartProxy@noreply.github.com; 
抄送: "下标越界-Mr.he"hedaode@qq.com; 
主题: Re: [SmartProxy] 开源许可 (#2)

@hedaode 感谢！也建议在项目中添加 LICENSE 文件方便大家对项目提交贡献。直接在 GitHub 点击文件列表上方、项目名旁边的 + 号（或者地址 https://github.com/hedaode/SmartProxy/new/master ），文件名填入 LICENSE，就可以在右边「Want to use a template?」选择 GPL 协议的模板。

**Comment by xingrz** [comment]
互相学习
